spring:
  application:
    name: satoken-study
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10s
    database: 0
    lettuce:
      pool:
        max-active: 200
        max-wait: -1 #连接池最大阻塞等待时间（使用负值标识没有限制）
        max-idle: 10
        min-idle: 0

server:
  port: 10001

sa-token:
  is-print: false