spring:
  application:
    name: redis-study
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yaoyaoling
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

  cache:
    type: redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:com/lilili/dao/*Mapper.xml
logging:
  level:
    com.lilili: debug
