spring:
  application:
    name: mybatisplus-study
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: yaoyaoling
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/lilili/dao/*Mapper.xml